{% set name = "mpl-template" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mpl_template-{{ version }}.tar.gz
  sha256: 9d5eac1da9b4a4cba6d7b2377d8c86799812c7a76caa680aef3581c822a59be9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=2.5.0

test:
  imports:
    - mpl_template
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://austinorr.github.io/mpl-template
  summary: 'mpl-template: matplotlib report template constructor'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - austinorr
    - ocefpaf
