{% set python_min = python_min|default("0.1a0") %}
{% set name = "mpl-template" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mpl_template-{{ version }}.tar.gz
  sha256: 33bd3f80160dfa39dcc341384cc5dd0c44d30b15a967723cfdf49c5d78a5ac3c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - setuptools >=64.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=2.5.0

test:
  imports:
    - mpl_template
  commands:
    - pip check
  requires:
    - python ={{ python_min }}
    - pip

about:
  home: https://austinorr.github.io/mpl-template
  summary: 'mpl-template: matplotlib report template constructor'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - austinorr
    - ocefpaf
